tokuhirom/Test-TCP

cpanfile, lib/Net/EmptyPort.pm, lib/Test/TCP.pm, t/01_simple.t, t/02_abrt.t, t/03_return_when_sigterm.t, t/04_die.t, t/06_nest.t, t/08_exit.t, t/09_fork.t, t/10_oo.t, t/11_net_empty_port.t, t/12_pass_wait_port_options.t, t/13_undef_port.t, t/Server.pm
This PR adds IPv6 support to Test::TCP.
The commits basically makes following changes to the public functions to add support for IPv6 while maintaining backwards compatibility:
* accept hash-style arguments
* recognize `host` parameter in the hash-style arguments, and bind to the specified address
* the default value of the `host` parameter is `127.0.0.1`
If the design and implementation seems fine, I would update the documents.
=> IPv6 support

lib/Net/EmptyPort.pm, t/11_net_empty_port.t
The PR adds a function named `Net::EmptyPort::can_bind` to fulfill the purpose.
Such capability is useful in checking whether tests should be run in IPv6 as well (with the function it can be tested simply by `can_bind('::1')`).
=> add function that checks if apps can bind to certain address (and port)

cpanfile
EmptyPort.pm uses IO::Socket::IP so it is not a test-only dependency.
Unless one have IO::Socket::IP installed already this means that dist simply fails to compile despite installing all declared dependencies.
=> IO::Socket::IP is required not only on test time

t/01_simple.t, t/11_net_empty_port.t
This prevents tests from dying and counting as FAIL on systems that don't support `IPV6_V6ONLY`.
=> check whether the OS implements IPV6_V6ONLY before using it

t/10_oo.t
Depending on various versions, system performance, etc. this test could
end up hitting 'done_testing' before the final note is produced in the
child process.
In stable Test::More/Test::Sharedfork there is a bug in that the tests
pass despite stuff happening after done_testing. In the new Test::* code
this is detected and considered a fatal error (to prevent false passes).
This patch makes the child exit after the last event, the parent waits
on the childs PID before calling done_testing. This ensures the child
can finish its work before the parent calls done_testing.
=> Fix race condition in t/10_oo.t

Changes, lib/Net/EmptyPort.pm, lib/Test/TCP.pm, t/14_listen.t
This avoids the race condition of another process binding to the port
before the server code can.
=> Add listen_socket function and listen option

lib/Net/EmptyPort.pm, t/11_net_empty_port.t
be316f1f worked around a core perl bug[1] which causes Perl < 5.24.0
to DESTROY the IO::Socket::IP object too late, causing the empty port
to not actually be empty if it was used immediately.
Unfortunately, this change was lost in ba745fd1, which again put the
return of `can_bind` on the stack along with the actual return value,
re-instating the bug.
Split the statement across two statements again, and add a comment on
the importance of preserving it.
[1] https://rt.perl.org/Public/Bug/Display.html?id=124248
Fixes #50
=> Ensure that IO::Socket::IP is DESTROY'd before can_bind returns

t/11_net_empty_port.t
Currently, a test fails if `/proc/sys/net/ipv4/ip_nonlocal_bind` is enabled.
This PR adds a check for that setting being present & enabled, and skips the test if so.
=> Avoid test failures if ip_nonlocal_bind is enabled

lib/Net/EmptyPort.pm
The root cause of #43 seems to be that wait_port/check_port logic does not consider IPv6-enabled Windows hosts. This has been the case since IPv6 support was added in https://github.com/tokuhirom/Test-TCP/commit/c0b7805f3b116825bf86b8d83ed8390c2b09cc6a.
For example, consider where an IPv6-enabled host has made this call:
`Net::EmptyPort::wait_port('::1', 9999, 10, 'tcp' )`
On a non-Windows host, both before and after this commit, the following will happen:
1. _Net::EmptyPort::wait_port()_ will call _check_port_ like this:
`if (check_port({ host => '::1', port => 9999, proto => 'tcp' })`
2. This will result in the following being set within check_port:
`($host, $port, $proto) = ('::1', 9999, 'tcp')`
3. That _check_port_ call will return true (unless something horrible has happened) and the …
=> Fix issue #43 - Make MSWin32 use check_port in the same way other platforms do.

lib/Net/EmptyPort.pm
=> Revert "Fix issue #43 - Make MSWin32 use check_port in the same way other platforms do."

lib/Net/EmptyPort.pm, lib/Test/TCP/CheckPort.pm
As discussed in #53, issue #43 is caused because _wait_port_/_check_port_ logic does not consider IPv6-enabled Windows hosts. This pull request attempts to fix this by modifying Test::TCP::CheckPort and its caller to pass `host` as well as `port` and `proto`.
An attempt at backwards compatibility has been made in that Test::TCP::CheckPort will still behave in the same way if passed only two arguments.
All tests pass on Win7 & Win10 with these changes.
=> Make Test::TCP::CheckPort able to pass hashref containing $host.

xt/04_dependents.t
And remove Monoceros because its test is broken. Some author's tests are failed by missing some modules(they are not installed by cpanm by default).
=> Don't run author tests for testing Modules

lib/Test/TCP.pm, t/04_die.t, t/10_oo.t, t/11_net_empty_port.t, t/12_pass_wait_port_options.t
Here are some additional tests to improve the coverage. Please be aware that I do not have access to any MSWin32 systems so have not been able to test the changes on that platform.
These additional tests have shown up one thing which you might consider a bug: If the user does not supply a port to check_port() or to wait_port() (which the POD describes as being mandatory) the code does not test this but passes the undef along to IO::Socket::IP->new() which then throws the exception "Expected 'PeerService'". A couple of my new tests look for this error but you might consider it to be better if check_port() and wait_port() would check that a port has been supplied and carp something appropriate otherwise.
I hope you find this PR useful. The work has been done as part of the [CPAN PR …
=> Test coverage

lib/Net/EmptyPort.pm
To mitigate race condition, stop using rand for selecting unused port and let the kernel do it with calling `bind` with port 0 (in perl, passing `undef` for `LocalPort` argument).
Currently I'm testing this change on [h2o](https://github.com/h2o/h2o), and it seems to greatly improve the problem at least in Linux and OSX.
=> let the kernel select an empty port

lib/Net/EmptyPort.pm
Test::TCP do hack on Windows for checking port used.
https://github.com/tokuhirom/Test-TCP/commit/0f4510d8
But this way always return 0 with succeeded with empty port. This is not
expected behavior. So this change fix to call check_port if the port is
not defined.
fixes #60
=> don't run command when the port is empty

.appveyor.yml
Since there are so many Windows bugs, we need a Windows builder.
In the process I discovered that Test::Simple 1.302136 shipped with 5.28 works, while earlier versions shipped with 5.24 and 5.20 don't and cause tests to hang on WIndows Server 2016 (which is the version used by AppVeyor I think).
So we need to increase a lower bound on Test::Simple to improve Windows support
=> add AppVeyor Windows CI support

.travis.yml, t/01_simple.t, t/02_abrt.t, t/03_return_when_sigterm.t, t/04_die.t, t/06_nest.t, t/08_exit.t, t/09_fork.t, t/10_oo.t, t/12_pass_wait_port_options.t, t/13_undef_port.t
Apparently #58 failed because of some heisenbug in Travis itself.
I basically added a commit to remove extra dependencies which are needed with Module::Install-based distros but aren't needed with Minilla-based distros. And added 5.26 build, so now we build both 5.14 and 5.26
=> Fix tests for '.' in @INC - attempt 2

.gitignore, .mailmap, MANIFEST.SKIP, lib/Test/TCP.pm, xt/02_perlcritic.t
- put `MANIFEST` to `.gitignore`
- add committer aliases to `.mailmap` to avoid duplicate contributors in `META.json`
- add `MANIFEST.SKIP` so CI configs are not packaged and `make distcheck` passes
- add a `Test::Spellunker` stopword so Minilla spell checking passes
- remove non-existent dirs from `Perl::Critic` search paths so it doesn't display warnings
=> cosmetic fixes for minil dist

.appveyor.yml
All tests pass on Windows in current HEAD, see https://ci.appveyor.com/project/nponeccop/test-tcp/build/1.0.14 so the `cpanm install Test::Simple` line is unnecessary
=> Don't upgrade Test::Simple in Windows CI

Changes, lib/Net/EmptyPort.pm, t/11_net_empty_port.t
At the moment, the check_port function checks if a UDP port is being used by actually trying to bind to that port. This approach is racy.
This PR introduces a safer approach, where we send a UDP probe packet and see if an ICMP error is being delivered in response within 0.1 seconds. If not, we assume that the server is up.
I've also added a test case covering the use of check_port(UDP) which did not exist.
=> Fix race condition in check_port(UDP)

lib/Net/EmptyPort.pm
This PR addresses Win32 issues reported by https://github.com/tokuhirom/Test-TCP/issues/82 .
IO::Socket::IP has a portable "Blocking" option (F_SETFL is not defined under Win32), and Winsock uses a differenct set of error codes (see also  https://blogs.msdn.microsoft.com/japan_platform_sdkwindows_sdk_support_team_blog/2011/12/24/winsock-windows-socketsos123/ for CONNRESET).
=> Fix (Win32) portability issues

t/11_net_empty_port.t
=> specify 127.0.0.1 explicitly for binding UDP socket in test

.appveyor.yml, Changes, lib/Net/EmptyPort.pm, t/01_simple.t
The new `WSA*` constants are only supported since Perl 5.24 according
to `man perlport`.. So on older perls such as 5.20.3
the 11_empty_port.t test failed with "Undefined subroutine
&Errno::WSAECONNRESET" error.
Closes #88
=> Portability fixes for Win32 perl older than 5.24

lib/Net/EmptyPort.pm
In Windows, if there is a space in the path for perl (for example, a perl installed in a home directory or Program Files) then the command needs to be quoted or it will throw an error saying the command is not recognised.
Tested on Windows 10 using perl 5.30.2 installed using psperl
=> Quote executable name in Windows
